<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SlowFlow.Core\SlowFlow.Core.csproj" />
    <ProjectReference Include="..\SlowFlow.Infrastructure\SlowFlow.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
