[platformio]
default_envs = portenta_h7_m7

[env:portenta_h7_m7]
platform = ststm32@19.4.0
board = portenta_h7_m7
framework = arduino
build_type = debug
monitor_speed = 115200
test_framework = custom

build_flags =
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC

lib_ldf_mode = deep+

lib_deps =
  bblanchon/ArduinoJson@7.4.2
  olikraus/U8g2@2.36.17
  arduino-libraries/ArduinoModbus@1.0.9
  arduino-libraries/ArduinoRS485@1.1.1
  arduino-libraries/Arduino_PowerManagement@1.0.0
  knolleary/PubSubClient@2.8.0
